### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by frapik99** [KageDesu/Alpha-ABS#1]
Hi,
I have the following error when I try to run the game:

```
Alpha_ABS.js:1453 Using AlphaABS [Version: 110 ; Build: 568]SceneManager._printABSInfo @ Alpha_ABS.js:1453SceneManager.catchException @ Alpha_ABS.js:1442SceneManager.update @ rpg_managers.js:1717
rpg_managers.js:1756 TypeError: Cannot read property 'toUpperCase' of undefined
    at UIObject_SkillPanelItem_L._update (Alpha_ABS.js:12464)
    at new UIObject_SkillPanelItem_L (Alpha_ABS.js:12404)
    at Sprite_SkillPanelABS_L._initSkills2 (Alpha_ABS.js:12382)
    at Sprite_SkillPanelABS_L.refresh (Alpha_ABS.js:12372)
    at Window_EventItem.AlphaABS.LIB.Bar.Window_ItemList.initialize (Alpha_ABS.js:14057)
    at Window_EventItem.initialize (rpg_windows.js:4176)
    at new Window_EventItem (rpg_windows.js:4166)
    at Window_Message.createSubWindows (rpg_windows.js:4273)
    at Window_Message.initialize (rpg_windows.js:4249)
    at new Window_Message (rpg_windows.js:4236)
```

moreover:

```
rpg_managers.js:93 GET http://127.0.0.1:4000/data/ABSDataUser.json 404 (Not Found)
DataManager.loadDataFile @ rpg_managers.js:93DataManager.loadDatabase @ Alpha_ABS.js:1429Scene_Boot.create @ rpg_scenes.js:162SceneManager.changeScene @ rpg_managers.js:1810SceneManager.updateMain @ rpg_managers.js:1789SceneManager.update @ rpg_managers.js:1714
Alpha_ABS.js:1076 Alpha ABS: Skill Heal not learned, not ABS type
Alpha_ABS.js:1076 Alpha ABS: Skill Spark not learned, not ABS type
Alpha_ABS.js:1076 Alpha ABS: Skill Fire not learned, not ABS type
Alpha_ABS.js:1076 Alpha ABS: Skill Heal not learned, not ABS type
Alpha_ABS.js:1076 Alpha ABS: Inited v.110 build 568
Alpha_ABS.js:896 GET http://127.0.0.1:4000/data/ABSKeys.rpgsave 404 (Not Found)SDK.loadDataFileWeb @ Alpha_ABS.js:896Input.loadSchemeABS @ Alpha_ABS.js:1865BattleManagerABS.init @ Alpha_ABS.js:3092Scene_Boot.start @ Alpha_ABS.js:9088SceneManager.updateScene @ rpg_managers.js:1824
SceneManager.updateMain @ rpg_managers.js:1790SceneManager.update @ rpg_managers.js:1714
Alpha_ABS.js:1076 Alpha ABS: Skill Heal not learned, not ABS type
Alpha_ABS.js:1076 Alpha ABS: Skill Spark not learned, not ABS type
Alpha_ABS.js:1076 Alpha ABS: Skill Fire not learned, not ABS type
Alpha_ABS.js:1076 Alpha ABS: Skill Heal not learned, not ABS type
```
I have followed exactly the video you share. I'm trying to play the game in the browser..

Any idea why?

EDIT: The same game exported for windows works.
EDIT2: I did a bit of debugging and the issue is due to ```AlphaABS.Key.symbol```, it is always empty I guess

Thanks

**Comment by frapik99** [comment]
Hi,
I found a quick and dirty solution:

```
Input.loadSchemeABS = function() {
        if(Utils.isNwjs()) {
        	if(SDK.isFile(AlphaABS.Key.FNAME)) {
            	AlphaABS.Key.symbol = SDK.readFile(AlphaABS.Key.FNAME);
        	} else {
        		Input.toDefaultABS();
        	}
        } else {
        	if(localStorage.getItem(AlphaABS.Key.FNAME)) {
        		AlphaABS.Key.symbol = SDK.readFileWeb(AlphaABS.Key.FNAME);
        	} else {
						Input.toDefaultABS();
        	/*	SDK.loadDataFileWeb(AlphaABS.Key.FNAME, function(data) {
        			AlphaABS.Key.symbol = data;
        		}, function() {
					Input.toDefaultABS();
				});*/
        	}
        }
    }
```

with the previous code no button are assigned if the file cannot be loaded.

**Comment by KageDesu** [comment]
Hi, thanks for  the bug report. But at the moment i do not have access to development. понедельник, 23 января 2017г., 18:26 +0300 от frapik99  notifications@github.com :

>Hi,
>I have the following error when I try to run the game:
>Alpha_ABS.js:1453 Using AlphaABS [Version: 110 ; Build: 568]SceneManager._printABSInfo @ Alpha_ABS.js:1453SceneManager.catchException @ Alpha_ABS.js:1442SceneManager.update @ rpg_managers.js:1717
rpg_managers.js:1756 TypeError: Cannot read property 'toUpperCase' of undefined
    at UIObject_SkillPanelItem_L._update (Alpha_ABS.js:12464)
    at new UIObject_SkillPanelItem_L (Alpha_ABS.js:12404)
    at Sprite_SkillPanelABS_L._initSkills2 (Alpha_ABS.js:12382)
    at Sprite_SkillPanelABS_L.refresh (Alpha_ABS.js:12372)
    at Window_EventItem.AlphaABS.LIB.Bar.Window_ItemList.initialize (Alpha_ABS.js:14057)
    at Window_EventItem.initialize (rpg_windows.js:4176)
    at new Window_EventItem (rpg_windows.js:4166)
    at Window_Message.createSubWindows (rpg_windows.js:4273)
    at Window_Message.initialize (rpg_windows.js:4249)
    at new Window_Message (rpg_windows.js:4236)

**Comment by frapik99** [comment]
No problem, are you still working on this project?

**Comment by KageDesu** [comment]
Yes, i returned to develop. Thanks for your fix. It will be work in next build.

**Comment by newbie678** [comment]
This solved one problem.
Fixed a problem with the title.
However, this solution caused another problem.
For example, <escapeOnBattle: 0> does not apply.
It acts as <escapeOnBattle: 1> regardless of the command.
