### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by isodidacte** [KageDesu/Alpha-ABS#11]
hello, 
I have a problem with the selection map of my characters, it's not an ABS map, but I still have a plugin bug when I remove a character to put the chosen one.
This bug was not present on the older version, I am in 1.2: 800.
here is the error:
"cannot read property 'reInitABS' of undefined"

Thank you for your help.

![developer tools - filecuserscobo-golovatenkodesktoppartie1devellopementarcanumsecondindex htmltest](https://user-images.githubusercontent.com/19922313/41510563-232b66be-7267-11e8-869f-1ad5eee72e9d.jpg)

**Comment by Dawntay101** [comment]
also having this bug :L

**Comment by KageDesu** [comment]
Thanks, i'll fix that soon

**Comment by KageDesu** [comment]
Fixed in build 903
