### ISSUE TITLE
rpgmaker mv 1.5.1(steam)- I get black screen error message: ABS: Support only RPG Maker MV 1.3.1 and above

### ISSUE THREAD

**Issue by blurymind** [KageDesu/Alpha-ABS#3]
Seems to be failing to detect my editor version
$.STRING_ERROR_VERSION = 

How do i disable this faulty error check?

**Comment by blurymind** [comment]
I disabled this line here:

	```
		// var v = Utils.RPGMAKER_VERSION.split('.');
			// if(v[0] < 1) {
				// throw new Error(Consts.STRING_ERROR_VERSION[SDK.isRU()]);
			// } else {
				// if(v[1] < 3) {
					// throw new Error(Consts.STRING_ERROR_VERSION[SDK.isRU()]);
				// } else {
					// if(v[1] == 3 && v[2] < 1)
						// throw new Error(Consts.STRING_ERROR_VERSION[SDK.isRU()]);
				// }
			// }
```

so it doesnt do the check

**Comment by blurymind** [comment]
apparently it thinks that I am running rpg maker version 1.2.0
:o 
which is what Utils.RPGMAKER_VERSION is returning if you are running the steam version of rpg maker mv 1.5.1

Perhaps we should notify enterbrain about this bug

**Comment by blurymind** [comment]
suggestion for the pluggin - for better debugging, I suggest you change the string error version line to say this:

```
$.STRING_ERROR_VERSION = 
 	["Running on Rpg Maker MV "+Utils.RPGMAKER_VERSION+" ABS: Support only RPG Maker MV 1.3.1 and above",'ABS: Обновите версию RPG Maker MV до 1.3.1 или выше'];
```

**Comment by blurymind** [comment]
for everyone else with this bug, put
`return true;
`
above this line
`var v = Utils.RPGMAKER_VERSION.split('.');`

its an easy fix

**Comment by blurymind** [comment]
I made a pull request that disables the version check, as a temporary fix for the steam version bug:
https://github.com/KageDesu/Alpha-ABS/pull/4
I also added a couple of useful little features, to make using the plugin less labour intensive

**Comment by blurymind** [comment]
I reported the bug on rpg maker forum:
https://forums.rpgmakerweb.com/index.php?threads/rpg-maker-mv-1-5-1-on-steam-utils-rpgmaker_version-returns-1-2.85397/

**Comment by KageDesu** [comment]
Thanks. It will be useful.
