### ISSUE TITLE
i want More skill slot.

### ISSUE THREAD

**Issue by qwerty7523** [KageDesu/Alpha-ABS#42]
i am using Alpha ABS [MV] Pro (b1245).
I have a question, so I don't think it's desirable to post it here, but I'd appreciate it if you could answer.
I look forward to your answer to this question at any time.

To make it simple,
i want More skill slot.
how can i make more skill slot?
No matter how hard I look, I don't know the answer

In the next version, I would appreciate it if you could add a way to increase the skill slot in the plugin setting.

**Comment by KageDesu** [comment]
More skill slots will be with update
